jarvis.conversations.dir=conversations
jarvis.training_data.dir=conversations
jarvis.scripts.dir=scripts
jarvis.voices.dir=scripts\\kokoro\\hf_cache\\voices
jarvis.mouth.api_base_url=http://127.0.0.1:8880
jarvis.ollama.api_base_url=http://127.0.0.1:11434
jarvis.ocular.api_base_url=http://127.0.0.1:8882
jarvis.ears.api_base_url=http://127.0.0.1:8881
jarvis.actuators.api_base_url=http://127.0.0.1:8084
